# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: Chicago }, { name: Copenhagen }])
#   Mayor.create(name: Emanuel, city: cities.first)

Post.create( :id =>1 , :user_id =>1, :title => "Welcome", :description => "We would like to thank you for visiting the site. Please invite all of your friends")

Post.create( :id =>100 , :user_id =>1, :title => "Sanitation", :description => "Sanitation generally refers to the provision of facilities and services for the safe disposal of human urine and faeces. Inadequate sanitation is a major cause of disease worldwide and improving sanitation is known to have a significant beneficial impact on health both in households and across communities. The word sanitation also refers to the maintenance of hygienic conditions, through services such as garbage collection and wastewater disposal.")
Post.create( :id =>101 , :user_id =>1, :title => "Water Sanitation", :description => "Diarrhoea claims the lives of 4,000 children a day. These children are dying because they do not have access to adequate sanitation or safe water. Their deaths, from common diseases, are preventable.Where there is nowhere safe and clean to go to the toilet, people are exposed to disease, lack of privacy, and indignity.Bad health caused by poor sanitation has a knockon effect on the family economy and nutrition.In many cultures women who have no access to a latrine must wait until it is dark to go to the toilet or have to walk long distances to find an isolated spot. Where there are no toilets girls are prevented from going to school.This slum has existed for 10 years and is in a shocking state, explains Ruby from Balar Math Slum, Dhaka, Bangladesh Hanging latrines feed straight into a rubbishfilled ditch in the middle of the slum.  5000 households here have no clean water and no sanitation. Many people get very ill here and I think it all stems from the open latrines. Smell the stench, its disgusting. We get fevers, coughs and terrible diarrhoea and there are no healthcare facilities that we can use. WaterAid helps communities to build somewhere safe and clean to go to the toilet. Improving sanitation not only improves health, but also peoples dignity and livelihoods. This short animation explains how total sanitation can be achieved and the improvements safe sanitation can bring")
Post.create( :id =>102 , :user_id =>1, :title => "Water Sanitation", :description => " About 2 billion people use unsafe toilets or defecate in the open.  Poor sanitation causes severe diarrhea, which kills 1.5 million children each year.  Smart investments in sanitation can reduce disease, increase family incomes, keep girls in school, help preserve the environment, and enhance human dignity.  ")
Post.create( :id =>103 , :user_id =>1, :title => "Global Sanitation", :description => "The UNWater Global Analysis and Assessment of Sanitation and DrinkingWater (GLAAS) report provides further reason for vigilance  resources are neither targeted nor apparently sufficient to sustain routine operation and maintenance of water and sanitation services. Thus, there is a serious risk of slipping backwards on gains already made. The analysis emerging from UNWater GLAAS also helps to identify the reasons behind the disparities in access to sanitation and drinkingwater among different regions, communities and income groups. ")
Post.create( :id =>104 , :user_id =>1, :title => "Hygiene Unicef", :description => "According to the WHO/UNICEF Joint Monitoring Programme for Water Supply and Sanitation (JMP), 37% per cent of the developing worlds population 2 billion people lack improved sanitation facilities, and over 780 million people still use unsafe drinking water sources. Inadequate access to safe water and sanitation services, coupled with poor hygiene practices, kills and sickens thousands of children every day, and leads to impoverishment and diminished opportunities for thousands more.")
Post.create( :id =>105 , :user_id =>1, :title => "Journal of Water", :description => "This years conference will offer participants nearly 40 networking and workshop opportunities, over 200 academic presentations, and the chance to interact with a diverse group of water, health, hygiene and development thoughtleaders from around the world. A schedule of side events may be found here. Themes for the 2012 Conference include Monitoring and Evaluation for Sustainability; Ecosystem Protection and Drinking Water Safety; WaSH and Child Health; Southeastern US Water Challenges; Beyond 2015: Realizing Universal Access and Human Rights; Water, Energy and Climate; Making Sanitation Benefits Achievable and Sustainable for All; and Householdcentered WaSH.")
Post.create( :id =>106 , :user_id =>1, :title => "New Zealand", :description => "New Zealand enjoys high rainfall, especially along its west coast and the country is notable for its many large, and sometimes braided rivers. However, although the population is relatively small, the population density in North Island is much greater than in South Island where most of the rain falls.In rural communities, it remains commonplace for houses to be served by their own private supply  usually by the collection of rainwater from roofs. This practice is not constrained by any regulations.")

Post.create( :id =>107 , :user_id =>1, :title => "NZ Water Supply", :description => "The low level of water pollution and the relative abundance of rainfall ensures that water shortages are relatively uncommon. Regional authorities provide abstraction, treatment and distribution infrastructure to most developed areas. Some systems such as that serving Christchurch was of sufficiently good quality than no disinfection of final water was practised until the recent earthquake events. About 87% of the population receives drinking water from local authorities, including 53 District Councils and 5 Unitary Authorities. Domestic water usage demand is relatively poorly documented with few authorities collecting relevant or reliable information and several relying exclusively on abstraction volumes as a surrogate for use. For example, in Nelson residential water use was estimated at 180 liter/person/day while total water use including commercial use and public buildings was estimated at 500 liter/person/day.")

Post.create( :id =>108 , :user_id =>1, :title => "A threatening situation", :description => "1.1 billion people lack access to safe drinking water. 2.6 billion people lack adequate sanitation. 1.8 million people die every year from diarrhoeal diseases, including 90 % of children under 5. This situation is no longer bearable.")


Post.create( :id =>109 , :user_id =>1, :title => "Benefits of Sanitation", :description => "What are the expected outcomes of meeting the MDG 7 Target 10? In the context of development challenges, it is a great priority to focus on water supply and sanitation. Indeed, it is an imperative to respect human values, it provides good health and ensures economic benefits.")


Post.create( :id =>110 , :user_id =>1, :title => "Improving the community", :description => "Safe drinking water and basic sanitation is of crucial importance to the preservation of human health, especially among children. Waterrelated diseases are the most common cause of illness and death among the poor of developing countries. According to the World Health Organization, 1.6 million deaths of children per year can be attributed to unsafe water, poor sanitation, and lack of hygiene. The WHO/UNICEF Joint Monitoring Program evaluated that meeting the MDG Target 10 would avert 470 000 deaths per year.")


Post.create( :id =>111 , :user_id =>1, :title => "Improving Life Expectancy", :description => "From the age of 0 to 4 years, the cruel toll of child mortality may be reduced.From the age of 5 to 14 years, far more children, especially girls, could go to school if they had adequate drinking water and sanitation facilities. It would enable children to escape from their familiespoverty.From the age of 15 to 59 years, productivity gains would be achieved with improved water and sanitation facilities.People older than 60 could expect to live longer.")

Post.create( :id =>112 , :user_id =>1, :title => "Water, Sanitation & Hygiene", :description => "About 2 billion people use unsafe toilets or defecate in the open.  Poor sanitation causes severe diarrhea, which kills 1.5 million children each year.  Smart investments in sanitation can reduce disease, increase family incomes, keep girls in school, help preserve the environment, and enhance human dignity. ")




Post.create( :id =>113 , :user_id =>1, :title => "Sanitation", :description => "Sanitation generally refers to the provision of facilities and services for the safe disposal of human urine and faeces. Inadequate sanitation is a major cause of disease worldwide and improving sanitation is known to have a significant beneficial impact on health both in households and across communities. The word sanitation also refers to the maintenance of hygienic conditions, through services such as garbage collection and wastewater disposal.")
Post.create( :id =>114 , :user_id =>1, :title => "Water Sanitation", :description => "Diarrhoea claims the lives of 4,000 children a day. These children are dying because they do not have access to adequate sanitation or safe water. Their deaths, from common diseases, are preventable.Where there is nowhere safe and clean to go to the toilet, people are exposed to disease, lack of privacy, and indignity.Bad health caused by poor sanitation has a knockon effect on the family economy and nutrition.In many cultures women who have no access to a latrine must wait until it is dark to go to the toilet or have to walk long distances to find an isolated spot. Where there are no toilets girls are prevented from going to school.This slum has existed for 10 years and is in a shocking state, explains Ruby from Balar Math Slum, Dhaka, Bangladesh Hanging latrines feed straight into a rubbishfilled ditch in the middle of the slum.  5000 households here have no clean water and no sanitation. Many people get very ill here and I think it all stems from the open latrines. Smell the stench, its disgusting. We get fevers, coughs and terrible diarrhoea and there are no healthcare facilities that we can use. WaterAid helps communities to build somewhere safe and clean to go to the toilet. Improving sanitation not only improves health, but also peoples dignity and livelihoods. This short animation explains how total sanitation can be achieved and the improvements safe sanitation can bring")
Post.create( :id =>115 , :user_id =>1, :title => "Water Sanitation and Hygiene", :description => " About 2 billion people use unsafe toilets or defecate in the open.  Poor sanitation causes severe diarrhea, which kills 1.5 million children each year.  Smart investments in sanitation can reduce disease, increase family incomes, keep girls in school, help preserve the environment, and enhance human dignity.  ")
Post.create( :id =>116 , :user_id =>1, :title => "Global  Sanitation", :description => "The UNWater Global Analysis and Assessment of Sanitation and DrinkingWater (GLAAS) report provides further reason for vigilance  resources are neither targeted nor apparently sufficient to sustain routine operation and maintenance of water and sanitation services. Thus, there is a serious risk of slipping backwards on gains already made. The analysis emerging from UNWater GLAAS also helps to identify the reasons behind the disparities in access to sanitation and drinkingwater among different regions, communities and income groups. ")
Post.create( :id =>117 , :user_id =>1, :title => "Hygiene Unicef", :description => "According to the WHO/UNICEF Joint Monitoring Programme for Water Supply and Sanitation (JMP), 37% per cent of the developing worlds population 2 billion people lack improved sanitation facilities, and over 780 million people still use unsafe drinking water sources. Inadequate access to safe water and sanitation services, coupled with poor hygiene practices, kills and sickens thousands of children every day, and leads to impoverishment and diminished opportunities for thousands more.")
Post.create( :id =>118 , :user_id =>1, :title => "Journal of Development", :description => "This years conference will offer participants nearly 40 networking and workshop opportunities, over 200 academic presentations, and the chance to interact with a diverse group of water, health, hygiene and development thoughtleaders from around the world. A schedule of side events may be found here. Themes for the 2012 Conference include Monitoring and Evaluation for Sustainability; Ecosystem Protection and Drinking Water Safety; WaSH and Child Health; Southeastern US Water Challenges; Beyond 2015: Realizing Universal Access and Human Rights; Water, Energy and Climate; Making Sanitation Benefits Achievable and Sustainable for All; and Householdcentered WaSH.")
Post.create( :id =>119 , :user_id =>1, :title => "New Zealand", :description => "New Zealand enjoys high rainfall, especially along its west coast and the country is notable for its many large, and sometimes braided rivers. However, although the population is relatively small, the population density in North Island is much greater than in South Island where most of the rain falls.In rural communities, it remains commonplace for houses to be served by their own private supply  usually by the collection of rainwater from roofs. This practice is not constrained by any regulations.")

Post.create( :id =>120 , :user_id =>1, :title => "NZ Water Supply", :description => "The low level of water pollution and the relative abundance of rainfall ensures that water shortages are relatively uncommon. Regional authorities provide abstraction, treatment and distribution infrastructure to most developed areas. Some systems such as that serving Christchurch was of sufficiently good quality than no disinfection of final water was practised until the recent earthquake events. About 87% of the population receives drinking water from local authorities, including 53 District Councils and 5 Unitary Authorities. Domestic water usage demand is relatively poorly documented with few authorities collecting relevant or reliable information and several relying exclusively on abstraction volumes as a surrogate for use. For example, in Nelson residential water use was estimated at 180 liter/person/day while total water use including commercial use and public buildings was estimated at 500 liter/person/day.")

Post.create( :id =>121 , :user_id =>1, :title => "A threatening situation", :description => "1.1 billion people lack access to safe drinking water. 2.6 billion people lack adequate sanitation. 1.8 million people die every year from diarrhoeal diseases, including 90 % of children under 5. This situation is no longer bearable.")


Post.create( :id =>122 , :user_id =>1, :title => "Benefits of Sanitation", :description => "What are the expected outcomes of meeting the MDG 7 Target 10? In the context of development challenges, it is a great priority to focus on water supply and sanitation. Indeed, it is an imperative to respect human values, it provides good health and ensures economic benefits.")


Post.create( :id =>123 , :user_id =>1, :title => "Improving the community", :description => "Safe drinking water and basic sanitation is of crucial importance to the preservation of human health, especially among children. Waterrelated diseases are the most common cause of illness and death among the poor of developing countries. According to the World Health Organization, 1.6 million deaths of children per year can be attributed to unsafe water, poor sanitation, and lack of hygiene. The WHO/UNICEF Joint Monitoring Program evaluated that meeting the MDG Target 10 would avert 470 000 deaths per year.")


Post.create( :id =>124 , :user_id =>1, :title => "Improving Life Expectancy", :description => "From the age of 0 to 4 years, the cruel toll of child mortality may be reduced.From the age of 5 to 14 years, far more children, especially girls, could go to school if they had adequate drinking water and sanitation facilities. It would enable children to escape from their familiespoverty.From the age of 15 to 59 years, productivity gains would be achieved with improved water and sanitation facilities.People older than 60 could expect to live longer.")

Post.create( :id => 125, :user_id =>1, :title => "Water, Sanitation & Hygiene", :description => "About 2 billion people use unsafe toilets or defecate in the open.  Poor sanitation causes severe diarrhea, which kills 1.5 million children each year.  Smart investments in sanitation can reduce disease, increase family incomes, keep girls in school, help preserve the environment, and enhance human dignity. ")



Post.create( :id =>126, :user_id =>1, :title => "Sanitation", :description => "Sanitation generally refers to the provision of facilities and services for the safe disposal of human urine and faeces. Inadequate sanitation is a major cause of disease worldwide and improving sanitation is known to have a significant beneficial impact on health both in households and across communities. The word sanitation also refers to the maintenance of hygienic conditions, through services such as garbage collection and wastewater disposal.")
Post.create( :id =>127 , :user_id =>1, :title => "Water Sanitation", :description => "Diarrhoea claims the lives of 4,000 children a day. These children are dying because they do not have access to adequate sanitation or safe water. Their deaths, from common diseases, are preventable.Where there is nowhere safe and clean to go to the toilet, people are exposed to disease, lack of privacy, and indignity.Bad health caused by poor sanitation has a knockon effect on the family economy and nutrition.In many cultures women who have no access to a latrine must wait until it is dark to go to the toilet or have to walk long distances to find an isolated spot. Where there are no toilets girls are prevented from going to school.This slum has existed for 10 years and is in a shocking state, explains Ruby from Balar Math Slum, Dhaka, Bangladesh Hanging latrines feed straight into a rubbishfilled ditch in the middle of the slum.  5000 households here have no clean water and no sanitation. Many people get very ill here and I think it all stems from the open latrines. Smell the stench, its disgusting. We get fevers, coughs and terrible diarrhoea and there are no healthcare facilities that we can use. WaterAid helps communities to build somewhere safe and clean to go to the toilet. Improving sanitation not only improves health, but also peoples dignity and livelihoods. This short animation explains how total sanitation can be achieved and the improvements safe sanitation can bring")
Post.create( :id =>128 , :user_id =>1, :title => "Water Sanitation and Hygiene", :description => " About 2 billion people use unsafe toilets or defecate in the open.  Poor sanitation causes severe diarrhea, which kills 1.5 million children each year.  Smart investments in sanitation can reduce disease, increase family incomes, keep girls in school, help preserve the environment, and enhance human dignity.  ")
Post.create( :id =>129 , :user_id =>1, :title => "Global Sanitation", :description => "The UNWater Global Analysis and Assessment of Sanitation and DrinkingWater (GLAAS) report provides further reason for vigilance  resources are neither targeted nor apparently sufficient to sustain routine operation and maintenance of water and sanitation services. Thus, there is a serious risk of slipping backwards on gains already made. The analysis emerging from UNWater GLAAS also helps to identify the reasons behind the disparities in access to sanitation and drinkingwater among different regions, communities and income groups. ")
Post.create( :id =>130 , :user_id =>1, :title => "Hygiene Unicef", :description => "According to the WHO/UNICEF Joint Monitoring Programme for Water Supply and Sanitation (JMP), 37% per cent of the developing worlds population 2 billion people lack improved sanitation facilities, and over 780 million people still use unsafe drinking water sources. Inadequate access to safe water and sanitation services, coupled with poor hygiene practices, kills and sickens thousands of children every day, and leads to impoverishment and diminished opportunities for thousands more.")
Post.create( :id =>131 , :user_id =>1, :title => "Journal of Sanitation", :description => "This years conference will offer participants nearly 40 networking and workshop opportunities, over 200 academic presentations, and the chance to interact with a diverse group of water, health, hygiene and development thoughtleaders from around the world. A schedule of side events may be found here. Themes for the 2012 Conference include Monitoring and Evaluation for Sustainability; Ecosystem Protection and Drinking Water Safety; WaSH and Child Health; Southeastern US Water Challenges; Beyond 2015: Realizing Universal Access and Human Rights; Water, Energy and Climate; Making Sanitation Benefits Achievable and Sustainable for All; and Householdcentered WaSH.")
Post.create( :id =>132 , :user_id =>1, :title => "New Zealand", :description => "New Zealand enjoys high rainfall, especially along its west coast and the country is notable for its many large, and sometimes braided rivers. However, although the population is relatively small, the population density in North Island is much greater than in South Island where most of the rain falls.In rural communities, it remains commonplace for houses to be served by their own private supply  usually by the collection of rainwater from roofs. This practice is not constrained by any regulations.")

Post.create( :id =>133 , :user_id =>1, :title => "NZ Water Supply", :description => "The low level of water pollution and the relative abundance of rainfall ensures that water shortages are relatively uncommon. Regional authorities provide abstraction, treatment and distribution infrastructure to most developed areas. Some systems such as that serving Christchurch was of sufficiently good quality than no disinfection of final water was practised until the recent earthquake events. About 87% of the population receives drinking water from local authorities, including 53 District Councils and 5 Unitary Authorities. Domestic water usage demand is relatively poorly documented with few authorities collecting relevant or reliable information and several relying exclusively on abstraction volumes as a surrogate for use. For example, in Nelson residential water use was estimated at 180 liter/person/day while total water use including commercial use and public buildings was estimated at 500 liter/person/day.")

Post.create( :id =>134 , :user_id =>1, :title => "A threatening situation", :description => "1.1 billion people lack access to safe drinking water. 2.6 billion people lack adequate sanitation. 1.8 million people die every year from diarrhoeal diseases, including 90 % of children under 5. This situation is no longer bearable.")


Post.create( :id =>135 , :user_id =>1, :title => "Benefits of Sanitation", :description => "What are the expected outcomes of meeting the MDG 7 Target 10? In the context of development challenges, it is a great priority to focus on water supply and sanitation. Indeed, it is an imperative to respect human values, it provides good health and ensures economic benefits.")


Post.create( :id =>136 , :user_id =>1, :title => "Improving the community", :description => "Safe drinking water and basic sanitation is of crucial importance to the preservation of human health, especially among children. Waterrelated diseases are the most common cause of illness and death among the poor of developing countries. According to the World Health Organization, 1.6 million deaths of children per year can be attributed to unsafe water, poor sanitation, and lack of hygiene. The WHO/UNICEF Joint Monitoring Program evaluated that meeting the MDG Target 10 would avert 470 000 deaths per year.")


Post.create( :id =>137 , :user_id =>1, :title => "Improving Life Expectancy", :description => "From the age of 0 to 4 years, the cruel toll of child mortality may be reduced.From the age of 5 to 14 years, far more children, especially girls, could go to school if they had adequate drinking water and sanitation facilities. It would enable children to escape from their familiespoverty.From the age of 15 to 59 years, productivity gains would be achieved with improved water and sanitation facilities.People older than 60 could expect to live longer.")

Post.create( :id =>138 , :user_id =>1, :title => "Water, Sanitation & Hygiene", :description => "About 2 billion people use unsafe toilets or defecate in the open.  Poor sanitation causes severe diarrhea, which kills 1.5 million children each year.  Smart investments in sanitation can reduce disease, increase family incomes, keep girls in school, help preserve the environment, and enhance human dignity. ")

